apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/ai-platform-manifests.git'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 