apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-service
  namespace: ai-platform
  annotations:
    kubernetes.io/change-cause: "Automated deployment from CI/CD pipeline"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nlp-service
  template:
    metadata:
      labels:
        app: nlp-service
    spec:
      containers:
      - name: nlp-service
        image: ${DOCKER_USERNAME}/nlp-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: OPENAI_API_KEY
        - name: MODEL_CACHE_SIZE
          value: "1024"
        - name: INFERENCE_THREADS
          value: "4"
        - name: ENABLE_MIXED_PRECISION
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10