apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-platform-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ai-platform
  endpoints:
    - port: web
      interval: 30s 