
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ai-platform
  name: python-ai-service-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: python-ai-service-binding
  namespace: ai-platform
subjects:
- kind: ServiceAccount
  name: python-ai-service-sa
  namespace: ai-platform
roleRef:
  kind: Role
  name: python-ai-service-role
  apiGroup: rbac.authorization.k8s.io
