# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "your-username"
    reviewers:
      - "reviewer-username"
    ignore:
      - dependency-name: "some-library"
        versions: ["1.x"]
    commit-message:
      prefix: "deps"
      include: scope
  - package-ecosystem: "pip"
    directory: "/path/to/python/project"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "auto"
    commit-message:
      include: dependency-name
